//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorMart.Web.SendSMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="SendSMSService.SendSMSWorldSoap")]
    public interface SendSMSWorldSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/sendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sendSMS(string FromEmailAddress, string CountryCode, string MobileNumber, string Message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSMSWorldSoapChannel : MotorMart.Web.SendSMSService.SendSMSWorldSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSMSWorldSoapClient : System.ServiceModel.ClientBase<MotorMart.Web.SendSMSService.SendSMSWorldSoap>, MotorMart.Web.SendSMSService.SendSMSWorldSoap {
        
        public SendSMSWorldSoapClient() {
        }
        
        public SendSMSWorldSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSMSWorldSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSWorldSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSWorldSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendSMS(string FromEmailAddress, string CountryCode, string MobileNumber, string Message) {
            return base.Channel.sendSMS(FromEmailAddress, CountryCode, MobileNumber, Message);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="SendSMSService.SendSMSWorldHttpGet")]
    public interface SendSMSWorldHttpGet {
        
        // CODEGEN: Generating message contract since the operation sendSMS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/SendSMSWorldHttpGet/sendSMSRequest", ReplyAction="http://www.webserviceX.NET/SendSMSWorldHttpGet/sendSMSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MotorMart.Web.SendSMSService.sendSMSResponse sendSMS(MotorMart.Web.SendSMSService.sendSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string FromEmailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string CountryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string MobileNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Message;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(string FromEmailAddress, string CountryCode, string MobileNumber, string Message) {
            this.FromEmailAddress = FromEmailAddress;
            this.CountryCode = CountryCode;
            this.MobileNumber = MobileNumber;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSMSWorldHttpGetChannel : MotorMart.Web.SendSMSService.SendSMSWorldHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSMSWorldHttpGetClient : System.ServiceModel.ClientBase<MotorMart.Web.SendSMSService.SendSMSWorldHttpGet>, MotorMart.Web.SendSMSService.SendSMSWorldHttpGet {
        
        public SendSMSWorldHttpGetClient() {
        }
        
        public SendSMSWorldHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSMSWorldHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSWorldHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSWorldHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MotorMart.Web.SendSMSService.sendSMSResponse MotorMart.Web.SendSMSService.SendSMSWorldHttpGet.sendSMS(MotorMart.Web.SendSMSService.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public string sendSMS(string FromEmailAddress, string CountryCode, string MobileNumber, string Message) {
            MotorMart.Web.SendSMSService.sendSMSRequest inValue = new MotorMart.Web.SendSMSService.sendSMSRequest();
            inValue.FromEmailAddress = FromEmailAddress;
            inValue.CountryCode = CountryCode;
            inValue.MobileNumber = MobileNumber;
            inValue.Message = Message;
            MotorMart.Web.SendSMSService.sendSMSResponse retVal = ((MotorMart.Web.SendSMSService.SendSMSWorldHttpGet)(this)).sendSMS(inValue);
            return retVal.@string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="SendSMSService.SendSMSWorldHttpPost")]
    public interface SendSMSWorldHttpPost {
        
        // CODEGEN: Generating message contract since the operation sendSMS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/SendSMSWorldHttpPost/sendSMSRequest", ReplyAction="http://www.webserviceX.NET/SendSMSWorldHttpPost/sendSMSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MotorMart.Web.SendSMSService.sendSMSResponse1 sendSMS(MotorMart.Web.SendSMSService.sendSMSRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string FromEmailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string CountryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string MobileNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Message;
        
        public sendSMSRequest1() {
        }
        
        public sendSMSRequest1(string FromEmailAddress, string CountryCode, string MobileNumber, string Message) {
            this.FromEmailAddress = FromEmailAddress;
            this.CountryCode = CountryCode;
            this.MobileNumber = MobileNumber;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public sendSMSResponse1() {
        }
        
        public sendSMSResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSMSWorldHttpPostChannel : MotorMart.Web.SendSMSService.SendSMSWorldHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSMSWorldHttpPostClient : System.ServiceModel.ClientBase<MotorMart.Web.SendSMSService.SendSMSWorldHttpPost>, MotorMart.Web.SendSMSService.SendSMSWorldHttpPost {
        
        public SendSMSWorldHttpPostClient() {
        }
        
        public SendSMSWorldHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSMSWorldHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSWorldHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSWorldHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MotorMart.Web.SendSMSService.sendSMSResponse1 MotorMart.Web.SendSMSService.SendSMSWorldHttpPost.sendSMS(MotorMart.Web.SendSMSService.sendSMSRequest1 request) {
            return base.Channel.sendSMS(request);
        }
        
        public string sendSMS(string FromEmailAddress, string CountryCode, string MobileNumber, string Message) {
            MotorMart.Web.SendSMSService.sendSMSRequest1 inValue = new MotorMart.Web.SendSMSService.sendSMSRequest1();
            inValue.FromEmailAddress = FromEmailAddress;
            inValue.CountryCode = CountryCode;
            inValue.MobileNumber = MobileNumber;
            inValue.Message = Message;
            MotorMart.Web.SendSMSService.sendSMSResponse1 retVal = ((MotorMart.Web.SendSMSService.SendSMSWorldHttpPost)(this)).sendSMS(inValue);
            return retVal.@string;
        }
    }
}
